insert into Contacts (street, house_nr, country_code, city, country) values ('Buell', '47807', null, 'Yumbel', 'Chile');
insert into Contacts (street, house_nr, country_code, city, country) values ('Killdeer', '93', '22-650', 'Łaszczów', 'Poland');
insert into Contacts (street, house_nr, country_code, city, country) values ('Grim', '7102', null, 'Xihe', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('East', '0', 'SLZ', 'Saint Lucia', 'Malta');
insert into Contacts (street, house_nr, country_code, city, country) values ('Fulton', '0', null, 'Kerek', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Oak Valley', '256', null, 'Qinjia', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Weeping Birch', '3', null, 'Negotin', 'Serbia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Schurz', '35', null, 'Jiupu', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Kipling', '038', '91505', 'Burbank', 'United States');
insert into Contacts (street, house_nr, country_code, city, country) values ('Cascade', '373', null, 'Desa Werasari', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Coolidge', '154', null, 'Cikaludan', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Old Gate', '23', '44830-000', 'Piritiba', 'Brazil');
insert into Contacts (street, house_nr, country_code, city, country) values ('Banding', '588', null, 'Sibiti', 'Republic of the Congo');
insert into Contacts (street, house_nr, country_code, city, country) values ('Corscot', '6019', '3304', 'Garupá', 'Argentina');
insert into Contacts (street, house_nr, country_code, city, country) values ('Del Mar', '82', null, 'T’et’ri Tsqaro', 'Georgia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Cottonwood', '13764', null, 'Chefchaouene', 'Morocco');
insert into Contacts (street, house_nr, country_code, city, country) values ('Fisk', '0', null, 'Ruoqiang', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Starling', '2', null, 'Yanchi', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Petterle', '46', '93300-000', 'Novo Hamburgo', 'Brazil');
insert into Contacts (street, house_nr, country_code, city, country) values ('6th', '5772', '82-210', 'Malbork', 'Poland');
insert into Contacts (street, house_nr, country_code, city, country) values ('Hoffman', '65', null, 'Jinghai', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Declaration', '99718', 'V4W', 'Aldergrove', 'Canada');
insert into Contacts (street, house_nr, country_code, city, country) values ('Novick', '0240', '8611', 'Tinambacan', 'Philippines');
insert into Contacts (street, house_nr, country_code, city, country) values ('Charing Cross', '4', '6202', 'Loay', 'Philippines');
insert into Contacts (street, house_nr, country_code, city, country) values ('Prairieview', '149', null, 'Begejci', 'Serbia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Del Sol', '1015', '5276', 'Castro Barros', 'Argentina');
insert into Contacts (street, house_nr, country_code, city, country) values ('Canary', '6329', null, 'Kasama', 'Zambia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Pierstorff', '4', '446849', 'Nurlat', 'Russia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Maryland', '6', null, 'Beizi', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Dawn', '44933', null, 'Da’an', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Oxford', '561', '673377', 'Kholbon', 'Russia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Clove', '9983', '5103', 'Caigangan', 'Philippines');
insert into Contacts (street, house_nr, country_code, city, country) values ('Mandrake', '422', '592 11', 'Žďár nad Sázavou Druhy', 'Czech Republic');
insert into Contacts (street, house_nr, country_code, city, country) values ('Farmco', '548', '172715', 'Velikooktyabr’skiy', 'Russia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Dorton', '759', '8507', 'Loreto', 'Philippines');
insert into Contacts (street, house_nr, country_code, city, country) values ('Maywood', '731', null, 'Dongkengkou', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Milwaukee', '8', '9959', 'Pliska', 'Bulgaria');
insert into Contacts (street, house_nr, country_code, city, country) values ('Orin', '3', '5172', 'Piquillín', 'Argentina');
insert into Contacts (street, house_nr, country_code, city, country) values ('Shoshone', '6380', 'A86', 'Leixlip', 'Ireland');
insert into Contacts (street, house_nr, country_code, city, country) values ('Hooker', '2849', '2430-482', 'São Pedro de Muel', 'Portugal');
insert into Contacts (street, house_nr, country_code, city, country) values ('Jenna', '52647', null, 'Koni-Djodjo', 'Comoros');
insert into Contacts (street, house_nr, country_code, city, country) values ('Mayer', '679', null, 'Yuqunweng', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Marcy', '7256', '6060-414', 'Rosmaninhal', 'Portugal');
insert into Contacts (street, house_nr, country_code, city, country) values ('Glendale', '9123', null, 'Kebonkaret', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Jana', '35939', '77-330', 'Czarne', 'Poland');
insert into Contacts (street, house_nr, country_code, city, country) values ('Harbort', '8866', '6219', 'Siaton', 'Philippines');
insert into Contacts (street, house_nr, country_code, city, country) values ('Grasskamp', '061', '10130', 'Phra Pradaeng', 'Thailand');
insert into Contacts (street, house_nr, country_code, city, country) values ('Sundown', '539', null, 'Cihurip Satu', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Stoughton', '035', null, 'Soanierana Ivongo', 'Madagascar');
insert into Contacts (street, house_nr, country_code, city, country) values ('Mayer', '287', null, 'Oujda', 'Morocco');
insert into Contacts (street, house_nr, country_code, city, country) values ('Nevada', '95', '40160', 'Mancha Khiri', 'Thailand');
insert into Contacts (street, house_nr, country_code, city, country) values ('Jenna', '39178', null, 'Uruobo-Okija', 'Nigeria');
insert into Contacts (street, house_nr, country_code, city, country) values ('Mcbride', '8', null, 'Duut', 'Mongolia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Havey', '05', null, 'Lyubeshiv', 'Ukraine');
insert into Contacts (street, house_nr, country_code, city, country) values ('Monica', '90', '37950-000', 'São Sebastião do Paraíso', 'Brazil');
insert into Contacts (street, house_nr, country_code, city, country) values ('Oak', '1843', '981-2501', 'Marumori', 'Japan');
insert into Contacts (street, house_nr, country_code, city, country) values ('Corben', '084', '95720-000', 'Garibaldi', 'Brazil');
insert into Contacts (street, house_nr, country_code, city, country) values ('Elmside', '873', '21003', 'San Luis Jilotepeque', 'Guatemala');
insert into Contacts (street, house_nr, country_code, city, country) values ('Longview', '6172', '9711', 'Marantao', 'Philippines');
insert into Contacts (street, house_nr, country_code, city, country) values ('7th', '964', '3116', 'Crespo', 'Argentina');
insert into Contacts (street, house_nr, country_code, city, country) values ('Morningstar', '592', null, 'Wadusari', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Ridgeway', '878', '4618', 'El Colorado', 'Argentina');
insert into Contacts (street, house_nr, country_code, city, country) values ('Forster', '20917', '45600-000', 'Itabuna', 'Brazil');
insert into Contacts (street, house_nr, country_code, city, country) values ('Hauk', '39845', null, 'Anaráchi', 'Greece');
insert into Contacts (street, house_nr, country_code, city, country) values ('Kingsford', '91', null, 'Colomi', 'Bolivia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Erie', '2782', null, 'Huallanca', 'Peru');
insert into Contacts (street, house_nr, country_code, city, country) values ('Holmberg', '3528', '4595-075', 'Eiriz', 'Portugal');
insert into Contacts (street, house_nr, country_code, city, country) values ('Logan', '68702', null, 'Shuinan', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Mendota', '863', 'R21', 'Bagenalstown', 'Ireland');
insert into Contacts (street, house_nr, country_code, city, country) values ('Linden', '3075', '51841', 'Kotli Lohārān', 'Pakistan');
insert into Contacts (street, house_nr, country_code, city, country) values ('Gerald', '71', null, 'Gaibei', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Cascade', '16726', null, 'Şabyā', 'Saudi Arabia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Buena Vista', '70', null, 'Pingdingbu', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Dixon', '022', '2260-100', 'Praia do Ribatejo', 'Portugal');
insert into Contacts (street, house_nr, country_code, city, country) values ('Thompson', '53591', null, 'Kankara', 'Nigeria');
insert into Contacts (street, house_nr, country_code, city, country) values ('Maple Wood', '06561', '77553-000', 'Ipueiras', 'Brazil');
insert into Contacts (street, house_nr, country_code, city, country) values ('Rowland', '6289', null, 'Zhaogezhuang', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Bultman', '9457', null, 'Kota Trieng', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Riverside', '41', null, 'Mogadishu', 'Somalia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Meadow Valley', '413', null, 'Bawshar', 'Oman');
insert into Contacts (street, house_nr, country_code, city, country) values ('Havey', '59', null, 'Banjar Paangkelod', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Southridge', '9685', null, 'Waepana', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Jenifer', '528', null, 'Baiyan', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Morning', '9', null, 'Kudus', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Schlimgen', '60', null, 'El Cubolero', 'Honduras');
insert into Contacts (street, house_nr, country_code, city, country) values ('West', '555', '67131', 'Naushahro Fīroz', 'Pakistan');
insert into Contacts (street, house_nr, country_code, city, country) values ('Raven', '6', null, 'Al Qaţīf', 'Saudi Arabia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Roxbury', '70643', null, 'Xinchong', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Armistice', '1', null, 'Zhumadian', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Service', '5687', '21-044', 'Trawniki', 'Poland');
insert into Contacts (street, house_nr, country_code, city, country) values ('Schiller', '3289', null, 'Tongyu', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Arapahoe', '9250', null, 'Panineungan', 'Indonesia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Boyd', '363', null, 'Yunga', 'Peru');
insert into Contacts (street, house_nr, country_code, city, country) values ('Stephen', '5928', null, 'Svrljig', 'Serbia');
insert into Contacts (street, house_nr, country_code, city, country) values ('Lillian', '0', null, 'Jiangxiangzhen', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Dakota', '67455', null, 'Shatian', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Sage', '57', null, 'Longtou’an', 'China');
insert into Contacts (street, house_nr, country_code, city, country) values ('Westerfield', '15450', '569 07', 'Radiměř', 'Czech Republic');
insert into Contacts (street, house_nr, country_code, city, country) values ('Barby', '65450', '2276', 'Kriel', 'South Africa');
insert into Contacts (street, house_nr, country_code, city, country) values ('Loeprich', '73', '314-0048', 'Kashima-shi', 'Japan');
